### ISSUE TITLE
Support for doom-modeline?

### ISSUE THREAD

**Issue by lambdacn** [dp12/parrot#1]
It seems doesn't work with [doom-modeline](https://github.com/seagle0128/doom-modeline)
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/22525327/47546520-340b3580-d924-11e8-9bf3-09da5a4fa00e.png">

**Comment by dp12** [comment]
Yes, it's on my TODO list. I'll try to run some experiments and see if I can get it working in doom.

**Comment by dp12** [comment]
Hmm, I tried just now and it appears to work out of the box (I'm using spacemacs). You have to do `M-x parrot-mode` once to disable it, and then call it one more time to enable the parrot. Same thing for the nyan cat.

Does that work for you?

**Comment by lambdacn** [comment]
Yes, thanks @dp12

**Comment by dp12** [comment]
As a note to future doom-modeline users, to get parrot and friends to show up in the modeline, you'll need to add the following to your `init.el` file:

    (nyan-mode)
    (parrot-mode)
