### ISSUE TITLE
Outstanding Fork

### ISSUE THREAD

**Issue by psionic-k** [dp12/parrot#14]
Regarding https://github.com/melpa/melpa/pull/8811#issuecomment-1859637403

The changes in https://github.com/positron-solutions/parrot/commits/master/ are available for cherry pick / diff etc.  The only changes that don't make sense to bring in via that method are the maintainer and homepage package headers.

Let's just decide what to do.  The worst outcome would be to fork the core XPM modeline animation work and maintain two copies.

Because we can use autoloads to defer the inclusion of functions for progress and org todo states, I think we can keep the package lightweight while supporting more than one basic integration.  If we go this direction, I should check my autoloads and attempt to make sure parrot-progress.el is not loaded unless its behavior is turned on.

Some packages go the direction of having a main package and then some extras packages.  It's probably too heavy in this case.

**Comment by dp12** [comment]
Thanks for opening this @psionic-k. I am currently traveling, but I will make sure to look at this after Christmas.

**Comment by dp12** [comment]
Actually,  I think your idea of having a `parrot-extras` repo alongside the existing one is an excellent way to go. If you are interested, you could be maintainer of it. It would significantly lower the bar for people wanting to add extra features to parrot, as people could push up even experimental things without feeling the need to polish them.

**Comment by psionic-k** [comment]
> If you are interested, you could be maintainer of it

Lol

Anyway I'll pick apart the core changes I need and maintain the extras separately.  IIRC animate forever and other changes to the animation options were all necessary to fix up the core so that integrations would interoperate better.
